import os

os.system("python3 trace_some.py 'fine/19*.png'")
os.system("python3 trace_some.py 'fine/20*.png'")
os.system("python3 trace_some.py 'fine/21*.png'")
os.system("python3 trace_some.py 'fine/22*.png'")
os.system("python3 trace_some.py 'fine/23*.png'")
os.system("python3 trace_some.py 'fine/24*.png'")
os.system("python3 trace_some.py 'fine/25*.png'")
os.system("python3 trace_some.py 'fine/26*.png'")
os.system("python3 trace_some.py 'fine/27*.png'")
os.system("python3 trace_some.py 'fine/28*.png'")
os.system("python3 trace_some.py 'fine/29*.png'")
os.system("python3 trace_some.py 'fine/30*.png'")
os.system("python3 trace_some.py 'fine/31*.png'")
os.system("python3 trace_some.py 'fine/32*.png'")
os.system("python3 trace_some.py 'fine/33*.png'")
os.system("python3 trace_some.py 'fine/34*.png'")
os.system("python3 trace_some.py 'fine/35*.png'")
os.system("python3 trace_some.py 'fine/36*.png'")
os.system("python3 trace_some.py 'fine/37*.png'")
os.system("python3 trace_some.py 'fine/38*.png'")
os.system("python3 trace_some.py 'fine/39*.png'")
os.system("python3 trace_some.py 'fine/40*.png'")